/**
 * One-click AI report summarization (mock). Produces an executive summary from report sections.
 */

/**
 * @param {Object} report - { title, sections: Array<{ title, content, type }> }
 * @returns {Promise<{ summary: string, bullets: string[] }>}
 */
export function generateReportSummary(report) {
  return new Promise((resolve) => {
    const sections = report?.sections || [];
    const title = report?.title || 'Report';

    const textParts = sections
      .filter((s) => s.type === 'text' && typeof s.content === 'string' && !s.content.startsWith('__'))
      .map((s) => (s.title ? `${s.title}: ` : '') + s.content.slice(0, 400))
      .join('\n\n');

    // Mock AI: build a short summary and 3-5 bullets from content
    const lower = (title + ' ' + textParts).toLowerCase();
    const bullets = [];

    if (lower.includes('unemployment') || lower.includes('labour')) {
      bullets.push('Unemployment rate declined to 2.1% in 2024, among the lowest in the GCC.');
    }
    if (lower.includes('gdp') || lower.includes('growth')) {
      bullets.push('Real GDP growth stabilised around 2%; non-oil sector expansion continues.');
    }
    if (lower.includes('population') || lower.includes('census')) {
      bullets.push('Population growth positive across all governorates; data supports regional planning.');
    }
    if (lower.includes('inflation') || lower.includes('cpi')) {
      bullets.push('CPI inflation contained; base year 2019.');
    }
    if (lower.includes('vision 2040') || lower.includes('ncsi')) {
      bullets.push('Analysis aligned with Oman Vision 2040 and NCSI statistical standards.');
    }
    if (bullets.length === 0) {
      bullets.push('Key findings and recommendations are presented in the full report.');
    }

    const summary =
      `This executive summary was generated by AI from the report "${title}". ` +
      `The report draws on NCSI and official sources covering the Sultanate of Oman. ` +
      (bullets.length > 0 ? `Key highlights: ${bullets[0].toLowerCase()} ${bullets.slice(1, 2).map((b) => b.toLowerCase()).join(' ')}.` : 'Review the sections below for details.');

    setTimeout(() => resolve({ summary, bullets: bullets.slice(0, 5) }), 800);
  });
}
